# Generated by Django 5.2.13 on 2026-04-12 18:54

import django.db.models.deletion
import labs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
                ('loinc_code', models.CharField(blank=True, max_length=20, verbose_name='Código LOINC')),
                ('category', models.CharField(choices=[('HEMATOLOGIA', 'Hematología'), ('BIOQUIMICA', 'Bioquímica'), ('LIPIDOS', 'Lípidos'), ('TIROIDES', 'Tiroides'), ('HIERRO', 'Hierro'), ('INFLAMACION', 'Inflamación'), ('ORINA', 'Orina'), ('VITAMINAS', 'Vitaminas'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Categoría')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('ref_min_male', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Rango mínimo (hombre)')),
                ('ref_max_male', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Rango máximo (hombre)')),
                ('ref_min_female', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Rango mínimo (mujer)')),
                ('ref_max_female', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Rango máximo (mujer)')),
                ('low_is_bad', models.BooleanField(default=True, verbose_name='Valor bajo es malo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Biomarcador',
                'verbose_name_plural': 'Biomarcadores',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('lab_name', models.CharField(blank=True, max_length=200, verbose_name='Laboratorio')),
                ('phenoage_years', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Edad biológica (PhenoAge)')),
                ('phenoage_delta_years', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Diferencia edad biológica-cronológica')),
                ('phenoage_missing', models.TextField(blank=True, default='', verbose_name='Marcadores faltantes para PhenoAge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Analítica',
                'verbose_name_plural': 'Analíticas',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodyCompositionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Altura (cm)')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grasa corporal (%)')),
                ('visceral_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Grasa visceral (nivel)')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa muscular (kg)')),
                ('water_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Agua (%)')),
                ('protein_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Proteína (%)')),
                ('bone_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa ósea (kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Composición corporal',
                'verbose_name_plural': 'Composiciones corporales',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ECGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('image', models.ImageField(upload_to=labs.models.ECGReport.ecg_image_upload_path, verbose_name='Imagen de ECG')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (bpm)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Electrocardiograma',
                'verbose_name_plural': 'Electrocardiogramas',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID público')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=labs.models.UserProfile.avatar_upload_path, verbose_name='Foto de perfil')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('biological_sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo biológico')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='BiomarkerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='labs.biomarker', verbose_name='Biomarcador')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.analysisreport', verbose_name='Analítica')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['biomarker__category', 'biomarker__order'],
                'unique_together': {('report', 'biomarker')},
            },
        ),
    ]
