# Generated by Django 5.2.13 on 2026-04-14 15:29

import django.db.models.deletion
import labs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_biomarker_remove_text_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ailicense',
            options={'verbose_name': 'AI license', 'verbose_name_plural': 'AI licenses'},
        ),
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='biomarker',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Biomarker', 'verbose_name_plural': 'Biomarkers'},
        ),
        migrations.AlterModelOptions(
            name='biomarkerresult',
            options={'ordering': ['biomarker__category', 'biomarker__order'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterModelOptions(
            name='bodycompositionreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Body composition', 'verbose_name_plural': 'Body compositions'},
        ),
        migrations.AlterModelOptions(
            name='ecgreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Electrocardiogram', 'verbose_name_plural': 'Electrocardiograms'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterField(
            model_name='ailicense',
            name='activated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activated at'),
        ),
        migrations.AlterField(
            model_name='ailicense',
            name='activated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Activated by'),
        ),
        migrations.AlterField(
            model_name='ailicense',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='AI API key'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='lab_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Laboratory'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='phenoage_delta_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Biological-chronological age difference'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='phenoage_missing',
            field=models.TextField(blank=True, default='', verbose_name='Missing markers for PhenoAge'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='phenoage_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Biological age (PhenoAge)'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='category',
            field=models.CharField(choices=[('HEMATOLOGIA', 'Hematology'), ('BIOQUIMICA', 'Biochemistry'), ('LIPIDOS', 'Lipids'), ('TIROIDES', 'Thyroid'), ('HIERRO', 'Iron'), ('INFLAMACION', 'Inflammation'), ('ORINA', 'Urine'), ('VITAMINAS', 'Vitamins'), ('OTRO', 'Other')], default='OTRO', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='low_is_bad',
            field=models.BooleanField(default=True, verbose_name='Low value is bad'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='ref_max_female',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Reference max (female)'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='ref_max_male',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Reference max (male)'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='ref_min_female',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Reference min (female)'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='ref_min_male',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Reference min (male)'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='biomarkerresult',
            name='biomarker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='labs.biomarker', verbose_name='Biomarker'),
        ),
        migrations.AlterField(
            model_name='biomarkerresult',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='biomarkerresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.analysisreport', verbose_name='Analysis'),
        ),
        migrations.AlterField(
            model_name='biomarkerresult',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='body_fat_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Body fat (%)'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='bone_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bone mass (kg)'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Muscle mass (kg)'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='protein_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Protein (%)'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='visceral_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Visceral fat (level)'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='water_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Water (%)'),
        ),
        migrations.AlterField(
            model_name='bodycompositionreport',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Heart rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='image',
            field=models.ImageField(upload_to=labs.models.ECGReport.ecg_image_upload_path, verbose_name='ECG image'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=labs.models.UserProfile.avatar_upload_path, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biological_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Biological sex'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='smoker',
            field=models.BooleanField(blank=True, null=True, verbose_name='Smoker'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public UUID'),
        ),
    ]
