# Generated by Django 5.2.8 on 2026-04-14 18:45

import labs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_alter_ailicense_options_alter_analysisreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=labs.models.AnalysisReport.pdf_upload_path, verbose_name='PDF'),
        ),
    ]
